### ISSUE TITLE
Fixed-length arrays are improperly parsed

### ISSUE THREAD

**Issue by PerilousApricot** [PerilousApricot/spark-ttree#26]
The following testcase fails:

https://github.com/PerilousApricot/spark-ttree/blob/a3c8e2a1d63d9069ab86a4d5125eaaa8a6b44647/src/test/java/edu/vanderbilt/accre/spark_ttree/TTreeDataSourceIntegrationTest.java#L55-L56

The first line (correctly) deserializes the 8-bit int variant, while the 2nd returns all zeros, though it is the correct shape. Tracing through, the correct bytestream is in the buffers (`ArrayI8: 0000000101010202028080808181818282827F7F7F7E7E7E7D7D7D` in hex), but something isn't lining up with the array interpretation

The tree is generated with https://github.com/PerilousApricot/spark-ttree/blob/bugfix/for-jim2/testdata/gen/make.py

**Comment by PerilousApricot** [comment]
I pushed additional test for the sliced array test I pointed out earlier. I'll strip it down to a faster-to-run unit test for you as well

**Comment by jpivarski** [comment]
This is fixed in PR #28. I'm going to close this issue even though that PR hasn't been merged yet—do that when you're ready.
