### ISSUE TITLE
Support boolean arrays

### ISSUE THREAD

**Issue by PerilousApricot** [PerilousApricot/spark-ttree#30]
Failing testcase can be found at https://github.com/PerilousApricot/spark-ttree/tree/bugfix/boolean-arrays

**Comment by jpivarski** [comment]
Do you mean

```
mvn -Dtest=TTreeDataSourceUnitTest#testArrayI1 test
```

which fails on line 262? I'm looking at it now.

**Comment by jpivarski** [comment]
See PR #32.
